Allow supervisor time before updating.
Also fail gracefully if it doesn't work.

diff --git a/packaging/datadog-agent-deb/postinst b/packaging/datadog-agent-deb/postinst
--- a/packaging/datadog-agent-deb/postinst
+++ b/packaging/datadog-agent-deb/postinst
@@ -8,14 +8,18 @@ case "$1" in
         adduser --system dd-agent --shell /bin/sh --no-create-home --quiet
         chown -R dd-agent /etc/dd-agent
 
-        #supervisorctl reread
-        #supervisorctl update
-
         if which invoke-rc.d >/dev/null 2>&1; then
             invoke-rc.d datadog-agent restart
         else
             /etc/init.d/datadog-agent restart
         fi
+
+        echo "Reading supervisor configuration."
+        supervisorctl reread || echo "Error reading supervisor configuration. Please restart supervisor."
+
+        echo "Updating supervisor configuration."
+        sleep 8     # Supervisor seems to need this time.
+        supervisorctl update || echo "Error updating supervisor configuration. Please restart supervisor."
     ;;
     abort-upgrade|abort-remove|abort-deconfigure)
     ;;
