Use the fact that the new postrm is run if the old one fails (#100).

diff --git a/packaging/datadog-agent/deb/postrm b/packaging/datadog-agent/deb/postrm
--- a/packaging/datadog-agent/deb/postrm
+++ b/packaging/datadog-agent/deb/postrm
@@ -1,12 +1,40 @@
 #! /bin/sh
 
-set -e 
+set -e
 
-supervisorctl reread
-supervisorctl update
+shutdown=0
 
-if which invoke-rc.d >/dev/null 2>&1; then
-    invoke-rc.d datadog-agent start
-else
-    /etc/init.d/datadog-agent start
+if [ -f /etc/supervisor/conf.d/ddagent.conf ]; then
+    suprunning=$(pgrep -fl supervisord)
+    if [ -n "$suprunning" ]; then
+	brokenconf=$(grep /var/tmp/datadog-supervisor.sock /etc/supervisor/conf.d/ddagent.conf | wc -l)
+	if [ $brokenconf -gt 0 ]; then
+	    brokenproc=$(supervisorctl status | grep 'no such file' | wc -l)
+	    if [ $brokenproc -gt 0 ]; then
+		echo "Your supervisor configuration is incorrect. I can fix it for you but I need to restart supervisor (with all its supervised processes listed below). If only datadog-agent processes are listed, this is a safe operation."
+		supervisorctl -c /etc/supervisor/conf.d/ddagent.conf status
+		read -p "Should I shut supervisord down for you? (Y/N) " bounce
+		if [[ "$bounce" == "y" || "$bounce" == "Y" ]]; then
+		    echo "Understood. Supervisord is going down now."
+		    supervisorctl -c /etc/supervisor/conf.d/ddagent.conf shutdown
+		    shutdown=1
+		else
+		    echo "I understand. You can read on how to fix supervisord manually at http://dtdg.co/fix-supervisor."
+		    echo "Aborting install now"
+		    exit 1
+		fi
+	    fi
+	fi
+    fi
+fi
+
+if [ $shutdown -eq 0 ]; then
+    supervisorctl reread
+    supervisorctl update
+
+    if which invoke-rc.d >/dev/null 2>&1; then
+	invoke-rc.d datadog-agent start
+    else
+	/etc/init.d/datadog-agent start
+    fi
 fi
