Move datadog config check to start command This allows us to stop the agent if the config file was present when starting the agent, but deleted before stopping it.

diff --git a/packaging/datadog-agent-base-deb/datadog-agent.init b/packaging/datadog-agent-base-deb/datadog-agent.init
--- a/packaging/datadog-agent-base-deb/datadog-agent.init
+++ b/packaging/datadog-agent-base-deb/datadog-agent.init
@@ -34,11 +34,6 @@ if [ ! -x $AGENTPATH ]; then
     exit 0
 fi
 
-if [ ! -f $AGENTCONF ]; then
-    echo "$AGENTCONF not found. Exiting."
-    exit 3
-fi
-
 check_status() {
     if [ -f $USE_SUPERVISOR ]; then
         # If the socket exists, we can use supervisorctl
@@ -89,6 +84,11 @@ check_status() {
 # Action to take
 case "$1" in
     start)
+        if [ ! -f $AGENTCONF ]; then
+            echo "$AGENTCONF not found. Exiting."
+            exit 3
+        fi
+
         check_status > /dev/null
         if [ $? -eq 0 ]; then
             echo "$DESC is already running"
@@ -139,13 +139,12 @@ case "$1" in
         su $AGENTUSER -c "$AGENTPATH info $@" || true
         su $AGENTUSER -c "$DOGSTATSDPATH info" || true
         if [ -f $USE_SUPERVISOR ]; then
-            su $AGENTUSER -c "$USE_SUPERVISOR info"
+            su $AGENTUSER -c "$USE_SUPERVISOR info" || true
         fi
         ;;
 
     status)
         check_status
-        exit $?
         ;;
 
     restart|force-reload)
@@ -159,4 +158,4 @@ case "$1" in
         ;;
 esac
 
-exit 0
+exit $?
diff --git a/packaging/datadog-agent-base-rpm/datadog-agent-redhat b/packaging/datadog-agent-base-rpm/datadog-agent-redhat
--- a/packaging/datadog-agent-base-rpm/datadog-agent-redhat
+++ b/packaging/datadog-agent-base-rpm/datadog-agent-redhat
@@ -36,11 +36,6 @@ else
     PYTHON="/usr/bin/python"
 fi
 
-if [ ! -f $AGENTCONF ]; then
-    echo "$AGENTCONF not found. Exiting."
-    exit 3
-fi
-
 # Source function library.
 . /etc/rc.d/init.d/functions
 
@@ -99,6 +94,11 @@ grab_status() {
 }
 
 start() {
+    if [ ! -f $AGENTCONF ]; then
+        echo "$AGENTCONF not found. Exiting."
+        exit 3
+    fi
+
     if [ -f $USE_SUPERVISOR ]; then
         # no need to test for status before daemon,
         # the daemon function does the right thing
