Update init.d scripts to check if datadog config is present before starting. Fix #544

diff --git a/packaging/datadog-agent-base-deb/datadog-agent.init b/packaging/datadog-agent-base-deb/datadog-agent.init
--- a/packaging/datadog-agent-base-deb/datadog-agent.init
+++ b/packaging/datadog-agent-base-deb/datadog-agent.init
@@ -14,6 +14,7 @@
 PATH=$PATH:/sbin # add the location of start-stop-daemon on Debian
 
 AGENTPATH="/usr/bin/dd-agent"
+AGENTCONF="/etc/dd-agent/datadog.conf"
 DOGSTATSDPATH="/usr/bin/dogstatsd"
 AGENTUSER="dd-agent"
 USE_SUPERVISOR="/usr/bin/dd-forwarder"
@@ -31,6 +32,11 @@ SUPERVISORD="/usr/bin/supervisord"
 if [ ! -x $AGENTPATH ]; then
     echo "$AGENTPATH not found. Exiting."
     exit 0
+fi
+
+if [ ! -f $AGENTCONF ]; then
+    echo "$AGENTCONF not found. Exiting."
+    exit 3
 fi
 
 check_status() {
diff --git a/packaging/datadog-agent-base-rpm/datadog-agent-redhat b/packaging/datadog-agent-base-rpm/datadog-agent-redhat
--- a/packaging/datadog-agent-base-rpm/datadog-agent-redhat
+++ b/packaging/datadog-agent-base-rpm/datadog-agent-redhat
@@ -23,6 +23,7 @@
 ### END INIT INFO
 
 AGENTPATH="/usr/share/datadog/agent/agent.py"
+AGENTCONF="/etc/dd-agent/datadog.conf"
 DOGSTATSDPATH="/usr/share/datadog/agent/dogstatsd.py"
 AGENTUSER="dd-agent"
 PIDPATH="/var/run/dd-agent/"
@@ -33,6 +34,11 @@ if [ -x "/usr/bin/python2.6" ]; then
     PYTHON="/usr/bin/python2.6"
 else
     PYTHON="/usr/bin/python"
+fi
+
+if [ ! -f $AGENTCONF ]; then
+    echo "$AGENTCONF not found. Exiting."
+    exit 3
 fi
 
 # Source function library.
