- agent.py, daemon.py: better logging, if debug mode is off log through syslog with level "info" instead of doing nothin - debian/postinst: create system user with a shell to be able to su -c - Updated license

diff --git a/debian/datadog-agent.init b/debian/datadog-agent.init
--- a/debian/datadog-agent.init
+++ b/debian/datadog-agent.init
@@ -1,17 +1,4 @@
 #!/bin/sh
-#
-###############################################################################
-# sd-agent
-#
-# Written by Boxed Ice <hello@boxedice.com>
-# A server monitoring daemon for www.serverdensity.com
-#
-# Licensed under Simplified BSD License (see LICENSE)
-#
-###############################################################################
-#
-# chkconfig: 345 85 15
-# description: Datadog Monitoring Agent
 
 ### BEGIN INIT INFO
 # Provides: dd-agent
@@ -23,60 +10,43 @@
 # Default-Stop: 0 1 6
 ### END INIT INFO
 
+set -e
+
+. /lib/lsb/init-functions
+
 AGENTPATH="/usr/bin/dd-agent"
 AGENTUSER="dd-agent"
-PIDPATH="/var/run/dd-agent/"
+PIDPATH="/var/run/sd-agent"
+NAME="dd-agent"
+DESC="datadog agent"
 
-[ -f $AGENTPATH ] || echo "/usr/bin/dd-agent not found"
-
-# Source function library.
-if [ -f /etc/init.d/functions ]; then
-        . /etc/init.d/functions
-fi
-
-if [ -f /etc/SuSE-release ]; then
-        . /etc/rc.status
-        rc_reset
-fi
+[ -x $AGENTPATH ] || echo "$AGENTPATH not found"
 
 # Action to take
 case "$1" in
   start)
+        echo -n "Starting $DESC: "
         if [ ! -f $PIDPATH ]; then
             mkdir -p $PIDPATH
-            chown $AGENTUSER $PIDPATH
         fi
-        su $AGENTUSER -c "python $AGENTPATH start init --clean"
-        if [ -f /etc/SuSE-release ]; then
-                rc_status -v
-        elif [ -f /etc/debian_version ] || [ -f /etc/lsb-release ] || [ -f /etc/gentoo-release ]; then
-                echo " Started"
-        else
-                success
-                echo
-        fi
-        echo
+        chown $AGENTUSER $PIDPATH
+        su $AGENTUSER -c "$AGENTPATH start init --clean"
+        echo "$NAME."
     ;;
   stop)
-        su $AGENTUSER -c "python $AGENTPATH stop init"
-
-        if [ -f /etc/SuSE-release ]; then
-                rc_status -v
-        elif [ -f /etc/debian_version ] || [ -f /etc/lsb-release ] || [ -f /etc/gentoo-release ]; then
-                echo " Stopped"
-        else
-                success
-                echo
-        fi
-        echo
+        echo -n "Stopping $DESC: "
+        $AGENTPATH stop init
+        echo "$NAME."
     ;;
   restart|force-reload)
         $0 stop
         $0 start
     ;;
   *)
-        echo "Usage: /etc/init.d/sd-agent start|stop|restart"
+        N=/etc/init.d/$NAME
+        echo "Usage: $N {start|stop|restart}"
         exit 1
+    ;;
 esac
 
 exit 0
