Running configcheck when starting the agent
Fix #838

diff --git a/packaging/datadog-agent-base-rpm/datadog-agent-redhat b/packaging/datadog-agent-base-rpm/datadog-agent-redhat
--- a/packaging/datadog-agent-base-rpm/datadog-agent-redhat
+++ b/packaging/datadog-agent-base-rpm/datadog-agent-redhat
@@ -100,6 +100,12 @@ start() {
         exit 3
     fi
 
+    su $AGENTUSER -c "$AGENTPATH configcheck" > /dev/null
+    if [ $? -ne 0 ]; then
+        echo -n "Invalid check configuration. Please run sudo /etc/init.d/datadog-agent configtest for more details."
+        echo -n "Resuming starting process."
+    fi
+
     if [ -f $USE_SUPERVISOR ]; then
         # no need to test for status before daemon,
         # the daemon function does the right thing
diff --git a/packaging/datadog-agent-deb/datadog-agent.init b/packaging/datadog-agent-deb/datadog-agent.init
--- a/packaging/datadog-agent-deb/datadog-agent.init
+++ b/packaging/datadog-agent-deb/datadog-agent.init
@@ -78,6 +78,12 @@ case "$1" in
             exit 0
         fi
 
+        su $AGENTUSER -c "$AGENTPATH configcheck" > /dev/null
+        if [ $? -ne 0 ]; then
+            log_daemon_msg "Invalid check configuration. Please run sudo /etc/init.d/datadog-agent configtest for more details."
+            log_daemon_msg "Resuming starting process."
+        fi
+
        
         log_daemon_msg "Starting $DESC (using supervisord)" "$NAME"
         start-stop-daemon --start --quiet --oknodo --exec $SUPERVISORD -- -c $SUPERVISOR_FILE --pidfile $SUPERVISOR_PIDFILE
